const images = {
    
    Like : require('../images/Like.png'),
    list_food : require('../images/list_food.png'),
    menu_hamburger : require('../images/menu_hamburger.png'),
    Rectangle : require('../images/Rectangle.png'),
    recycle : require('../images/Outline.png'),

    Search : require('../images/Search.png'),
    star_rating : require('../images/star_rating.png'),
    ticket : require('../images/ticket.png'),
    top_left : require('../images/top_left.png'),
    food1 : require('../images/food1.png'),
    food2 : require('../images/food2.png'),
    heart : require('../images/heart.png'),

    backgroundUp : require('../images/backgroundUp.png'),
    Inverse : require('../images/Inverse.png'),
    sushi_925x : require('../images/sushi_925x.png'),
    cornerup : require('../images/cornerup.png'),
    star : require('../images/star.png'),
    arrow_right : require('../images/arrow_right.png'),
    food : require('../images/food.png'),
    categories : require('../images/categories.png'),
    Bitmap : require('../images/Bitmap.png'),
    check : require('../images/check.png'),
    greencheck : require('../images/greencheck.png'),
    addcheck : require('../images/addcheck.png'),
    clock : require('../images/clock.png'),
    Oval : require('../images/Oval.png'),
    dropdown : require('../images/dropdown.png'),
    close : require('../images/close.png'),
    done : require('../images/done.png'),
    flag : require('../images/flag.png'),
    Bg : require('../images/Bg.png'),
    Fill : require('../images/Fill.png'),
    phone : require('../images/phone.png'),
    spoon : require('../images/spoon.png'),
    LIVREUSE : require('../images/LIVREUSE.png'),
    blackcheck : require('../images/blackcheck.png'),
}

export default images;
