export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS"
export const FACEBOOK_LOGIN_FAILURE = "FACEBOOK_LOGIN_FAILURE"
export const FACEBOOK_LOGIN_PROCESSING = "FACEBOOK_LOGIN_PROCESSING"
export const FACEBOOK_LOGIN_CLEAR = "FACEBOOK_LOGIN_CLEAR"
