export const FETCHING_DEALS = 'FETCHING_DEALS'
export const FETCHING_DEALS_SUCCESS = 'FETCHING_DEALS_SUCCESS'
export const FETCHING_DEALS_FAILURE = 'FETCHING_DEALS_FAILURE'

export const FETCHING_DISHES = 'FETCHING_DISHES'
export const FETCHING_DISHES_SUCCESS = 'FETCHING_DISHES_SUCCESS'
export const FETCHING_DISHES_FAILURE = 'FETCHING_DISHES_FAILURE'
